### ISSUE TITLE
動作確認用のポートフォワードの追加

### ISSUE THREAD

**Issue by irixjp** [infra-ci-book/bootstrap-host#1]
host:8082 => 192.168.33.12:80
host:8083 => 192.168.33.13:80
host:8084 => 192.168.33.14:80
host:8085 => 192.168.33.15:80

**Comment by kentarosasaki** [comment]
Done by this commit.
https://github.com/infra-ci-book/bootstrap-host/commit/3e6a124713d86e18c424df89accff91d53d3e5b6
