### ISSUE TITLE
統一鍵の設定

### ISSUE THREAD

**Issue by irixjp** [infra-ci-book/bootstrap-host#4]
予めリポジトリに秘密鍵と公開鍵を作成しておき、
全Vagrantサーバーへ公開鍵を登録しておく。

この鍵は7章8章で使う。

**Comment by irixjp** [comment]
参考ドキュメント
https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html

**Comment by habuka036** [comment]
config.ssh.private_key_path は秘密鍵を指定するためのパラメータらしいのと、これを設定してもうまく動かせなかったため、以下を参考にして /home/vagrant/.ssh/authorized_keys に公開鍵を追加するようにした。
https://stackoverflow.com/questions/30075461/how-do-i-add-my-own-public-key-to-vagrant-vm
