### ISSUE TITLE
ansbile-2.4.2.0がインストール出来ない

### ISSUE THREAD

**Issue by k3idx** [infra-ci-book/bootstrap-host#9]
突然すみません。
ansible-lintと同様にansible-2.4.2.0もEPELからインストールが出来なくなっています。
ansibleもマニュアルビルドされたRPMへと対応してもらえないでしょうか。

**Comment by yoshi-sheep** [comment]
当方も同じ現象に遭遇しました。Ansibleのバージョンを固定してインストールするため、EPELが提供するバージョンと異なるために生じるようです。
yum install（EPEL）ではなく、pipを使用してインストールすれば問題を回避できます。後の演習でも同じ問題が生じますが、Dockerfile内のyum installをすべてpipで置き換えると動作します。pipだとansibleのバージョン固定してもインストールできます。

**Comment by irixjp** [comment]
ご報告ありがとうございます。
いい手がないか試してみます。pip も1つの手ですね。

**Comment by irixjp** [comment]
一旦、最初のインストールは通るようになったと思います。
2.4.2 を support リポジトリに保存して、そこからインストールするように変更しています。

演習側はエラーになると思うので、そちらも確認してみます。

**Comment by irixjp** [comment]
演習7までは流れるようになったかと思います。
https://github.com/infra-ci-book/ketchup-vagrant-ansible/commit/443fb9f31f1e51dd5cc9043e03d6f606f2fe3113

**Comment by k3idx** [comment]
対応ありがとうございます。
まだChapter4を終えたところですが、パイプラインが正常終了するところまでは確認が出来ました。
また何か見つけたらIssue上げたいと思いますが、よろしくお願いします。

**Comment by yoshi-sheep** [comment]
修正ありがとうございました。
他のDockerfileも同じように修正することで、最後まで演習を終えることができました。locustの-tオプションがなぜかエラーとなってしまったのですが、バージョンを上げることで対応できました。
CIまたテストについてとても良い勉強になりました。執筆ありがとうございます。

**Comment by irixjp** [comment]
ご報告ありがとうございました！
